version: '3.9'

services:
  db:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - graphile_worker_poc_db_data:/bitnami/postgresql
  
  app:
    build:
      context: .
      target: dev
    ports:
      - '9090:9090'
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  graphile_worker_poc_db_data: